version: '3.8'

services:
  init-couchdb:
    image: curlimages/curl:latest
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - my-network
    entrypoint: >
      sh -c "
        curl -X PUT http://admin:admin@couchdb:5984/_users &&
        curl -X PUT http://admin:admin@couchdb:5984/_replicator &&
        curl -X PUT http://admin:admin@couchdb:5984/_global_changes
      "
  couchdb:
    image: couchdb:latest
    container_name: my-couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - "5984:5984"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  django:
    build: .
    container_name: my-django-app
    ports:
      - "8000:8000"
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - my-network
    command: sh -c "python generate_data.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  my-network:
    driver: bridge
