version: '3.8'

services:
  couchdb:
    image: couchdb:latest
    container_name: my-couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    ports:
      - "5984:5984"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    

  django:
    build: .
    container_name: my-django-app
    ports:
      - "8000:8000"
    depends_on:
      couchdb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - my-network
    command: sh -c "python generate_data.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: my-elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=admin
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-k", "-u", "elastic:admin", "-f", "https://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=30s"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  init-couchdb:
    image: curlimages/curl:latest
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - my-network
    entrypoint: >
      sh -c "
        curl -X PUT http://admin:admin@couchdb:5984/_users &&
        curl -X PUT http://admin:admin@couchdb:5984/_replicator &&
        curl -X PUT http://admin:admin@couchdb:5984/_global_changes
      "

  

networks:
  my-network:
    driver: bridge
